site_name: Food Geek Documentation

repo_url: https://github.com/JohnPPinto/food-geek-food-image-segmentation
repo_name: JohnPPinto/food-geek-food-image-segmentation

theme:
  name: material
  features:
    - navigation.tracking
    - toc.integrate
    - toc.follow
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
  palette:
    - scheme: slate 
      toggle:
        icon: material/brightness-4
        name: Switch to light mode    
      primary: teal
      accent: lime
    - scheme: default
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode
      primary: teal
      accent: purple 

plugins:
  - social
  - glightbox
  - search:
      lang: en
      

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/JohnPPinto
    - icon: fontawesome/brands/docker
      link: https://hub.docker.com/u/johnppinto
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/john77272002
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/john-p-pinto/

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true 
  - pymdownx.mark
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

copyright: |
  &copy; 2023 <a href="https://github.com/JohnPPinto"  target="_blank" rel="noopener">John Pinto</a>