name: Sync to Hugging Face hub
on:
  push: 
    paths: 
      - ./demo
      - Dockerfile

  # to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          lfs: true
      - name: Add remote 
        env:
          HF: ${{ secrets.FOOD_GEEK_HF_TOKEN }}
        run: git remote add space https://JohnPinto:$HF@huggingface.co/spaces/JohnPinto/food-geek
      - name: Push to hub
        env:
          HF: ${{ secrets.FOOD_GEEK_HF_TOKEN }}
        run: |
          git lfs install
          git lfs migrate import --everything
          git push --force https://JohnPinto:$HF@huggingface.co/spaces/JohnPinto/food-geek main